# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e901b6537a927c0a5fdfae0015b098eecfa2996ea2e721e88bd0b42a4a2db04ab33ea24d6d22d2b88415b1d0e3bcca4405dc2dac1cb9542e60b63796362434d

test:
  secret_key_base: 953ecd99da19ef58db42fc638dc937f43fcdc3db64e235d295751716845b9008f93870d95faa93ab7d43d886c55ab18a9866c3f9da8d2cc96b103bcf6fd4dd9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
